[package]
name = "learn_rust"
version = "0.1.0"
edition = "2021"
description = "A project for learning Rust programming"
authors = ["Your Name <your.email@example.com>"]
license = "MIT"

[dependencies]
